/**
 * The names of Allah as the Qur'an lists them, in 59:22–24.
 *
 * GENERATED by `npm run collection:names`. Do not edit by hand.
 *
 * Every character came over the wire from QuranEnc's Saheeh International
 * edition: the Arabic is the mushaf's, each title is their rendering of that
 * name in that verse, and each explanation is their own footnote on it.
 * Nothing here was written or remembered.
 *
 * ⚠️ This is deliberately NOT "the ninety-nine names". The statement that
 * Allah has ninety-nine is authentic — Bukhari 2736, Bukhari 7392, Muslim
 * 2677 — but the only enumerated lists are Tirmidhi 3507, graded Ḍaʿīf by all
 * three graders in the corpus, and Ibn Majah 3861, which lists different
 * names. The script's header carries the full working.
 *
 * ⚠️ No transliteration, on the same rule as `duas/hisn.ts` and `juz30.ts`.
 *
 * ⚠️ UNREVIEWED. The texts are the publisher's, but which names to present and
 * how to frame them is substance, and `docs/scholarly-review.md` is where that
 * is cleared.
 */
import { quran } from '../sources';
import type { Collection } from '../types';

export const QURANIC_NAMES: Collection = {
  id: 'quranic-names',
  title: 'The names of Allah',
  subtitle: 'As the Qur’an itself lists them, in Surat al-Hashr.',
  provider: 'quranenc',
  entries: [
  {
    id: "alim-al-ghayb",
    title: "Knower of the unseen and the witnessed",
    arabic: "عَٰلِمُ ٱلۡغَيۡبِ وَٱلشَّهَٰدَةِ",
    translation: "That which is absent, invisible, or beyond the perception of the senses or of the mind and therefore is unknown to man, except for what Allāh chooses to reveal.",
    note: "Qur’an 59:22",
    sources: [quran(59, 22, { surahName: 'Al-Hashr' })],
  },
  {
    id: "ar-rahman-ar-rahim",
    title: "the Entirely Merciful, the Especially Merciful",
    arabic: "ٱلرَّحۡمَٰنُ ٱلرَّحِيمُ",
    translation: "Ar-Raḥmān and ar-Raḥeem are two names of Allāh derived from the word \"raḥmah\" (mercy). In Arabic grammar both are intensive forms of \"merciful\" (i.e., extremely merciful). A complimentary and comprehensive meaning is intended by using both together. Raḥmān is used only to describe Allāh, while raḥeem might be used to describe a person as well. The Prophet (ﷺ) was described in the Qur’ān as raḥeem. Raḥmān is above the human level (i.e., intensely merciful). Since one usually understands intensity to be something of short duration, Allāh describes Himself also as raḥeem (i.e., continually merciful). Raḥmān also carries a wider meaning - merciful to all creation. Justice is a part of this mercy. Raḥeem includes the concept of speciality - especially and specifically merciful to the believers. Forgiveness is a part of this mercy. In addition, Raḥmān is adjectival, referring to an attribute of Allāh and is part of His essence. Raḥeem is verbal, indicating what He does: i.e., bestowing and implementing mercy.",
    note: "Qur’an 59:22",
    sources: [quran(59, 22, { surahName: 'Al-Hashr' })],
  },
  {
    id: "al-malik",
    title: "the Sovereign",
    arabic: "ٱلۡمَلِكُ",
    translation: "And owner of everything in existence.",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "al-quddus",
    title: "the Pure",
    arabic: "ٱلۡقُدُّوسُ",
    translation: "i.e., transcendent above any aspect belonging to His creation. Also, the possessor and grantor of blessings.",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "as-salam",
    title: "the Perfection",
    arabic: "ٱلسَّلَٰمُ",
    translation: "Literally, \"Free\" from any imperfection. Also, \"Peace\" or \"Soundness.\"",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "al-mumin",
    title: "the Grantor of Security",
    arabic: "ٱلۡمُؤۡمِنُ",
    translation: "And safety, i.e., reassurance that His promise is always fulfilled. Also, He who bestows faith.",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "al-muhaymin",
    title: "the Overseer",
    arabic: "ٱلۡمُهَيۡمِنُ",
    translation: "i.e., who observes, guards and protects. Also, \"the Criterion.\"",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "al-aziz",
    title: "the Exalted in Might",
    arabic: "ٱلۡعَزِيزُ",
    translation: "Honored for absolute power associated with wisdom and justice.",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "al-jabbar",
    title: "the Compeller",
    arabic: "ٱلۡجَبَّارُ",
    translation: "Whose irresistible force is without limitation; the one above all things who compels the creation to be as He wills it. Also, \"the Amender\" or \"the Rectifier\" who repairs, restores, completes or sets something right once again, out of His mercy.",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "al-mutakabbir",
    title: "the Superior",
    arabic: "ٱلۡمُتَكَبِّرُ",
    translation: "Supreme, complete and perfect in His essence, attributes and actions.",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "al-khaliq",
    title: "the Creator",
    arabic: "ٱلۡخَٰلِقُ",
    translation: "i.e., He who destined existence for His creation.",
    note: "Qur’an 59:24",
    sources: [quran(59, 24, { surahName: 'Al-Hashr' })],
  },
  {
    id: "al-bari",
    title: "the Producer",
    arabic: "ٱلۡبَارِئُ",
    translation: "i.e., He who brings His creation into existence.",
    note: "Qur’an 59:24",
    sources: [quran(59, 24, { surahName: 'Al-Hashr' })],
  },
  {
    id: "al-musawwir",
    title: "the Fashioner",
    arabic: "ٱلۡمُصَوِّرُ",
    translation: "i.e., He who gives every creation its particular form.",
    note: "Qur’an 59:24",
    sources: [quran(59, 24, { surahName: 'Al-Hashr' })],
  },
  {
    id: "al-hakim",
    title: "the Wise",
    arabic: "ٱلۡحَكِيمُ",
    translation: "Whose wisdom includes precise, perfect and absolute knowledge of all realities and outcomes, according to which He decrees and causes circumstances and occurrences.",
    note: "Qur’an 59:24",
    sources: [quran(59, 24, { surahName: 'Al-Hashr' })],
  },
  ],
};
