/**
 * The ninety-nine names of Allah.
 *
 * GENERATED by `npm run collection:names`. Do not edit by hand.
 *
 * The list, the transliteration and the English are from
 * www.99NamesofAllah.name, supplied by Iyad on 28 Aug 2026 and transcribed
 * into `scripts/data/99-names.json`. The vowelled Arabic is AlAdhan's,
 * matched to that list by transliteration AND position, because the PDF's own
 * Arabic column is reversed by its text layer and retyping Arabic is the one
 * thing this repository never does.
 *
 * ⚠️ The enumeration is a scholarly matter and this file takes a position on
 * it. The STATEMENT that Allah has ninety-nine names is authentic — Bukhari
 * 2736, Bukhari 7392, Muslim 2677. The enumerated LIST appears only in
 * Tirmidhi 3507, graded Ḍaʿīf by all three graders in the corpus, and Ibn
 * Majah 3861, which lists different names. The source used here holds that
 * the list in those narrations is an addition from later transmitters, and
 * derives its names from the Qur'an and authentic Sunnah following Ibn
 * al-Qayyim, Al-Ghazali, Ibn Hazm, Al-Qurtubi and Abd al-Razzaq al-Badr. That
 * is its claim, stated on its own page, and Iyad's decision to use it.
 * `docs/build-order.md` Phase 3 carries the full working.
 *
 * ⚠️ 14 of the 99 carry a `note` naming a verse, because the Qur'an
 * lists them itself in 59:22–24. The rest do not, and the file does not
 * pretend otherwise.
 *
 * ⚠️ UNREVIEWED on substance. The texts are the publishers'; whether this list
 * and this framing are right belongs in `docs/scholarly-review.md`.
 */
import { quran } from '../sources';
import type { Collection } from '../types';

export const QURANIC_NAMES: Collection = {
  id: 'quranic-names',
  title: 'The names of Allah',
  subtitle:
    'Ninety-nine of the names He calls Himself by. One a day is a season’s practice.',
  provider: 'ninetynine',
  arabicFrom: 'aladhan',
  meta: {
    category: 'belief',
    difficulty: 'deeper',
    estimatedMinutes: 20,
    beginnerPriority: 5,
    tags: ['arabic', 'vocabulary'],
    relatedContent: [{ kind: 'reference', id: 'who-is-allah' }],
  },
  entries: [
  {
    id: "n01",
    title: "Ar-Raḥmān",
    arabic: "الرَّحْمَنُ",
    translation: "The Most Merciful, The Entirely Merciful",
    note: "Qur’an 59:22",
    sources: [quran(59, 22, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n02",
    title: "Ar-Raḥīm",
    arabic: "الرَّحِيمُ",
    translation: "The Especially Merciful",
    note: "Qur’an 59:22",
    sources: [quran(59, 22, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n03",
    title: "Al-Malik",
    arabic: "الْمَلِكُ",
    translation: "The King and Owner of Dominion",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n04",
    title: "Al-Quddūs",
    arabic: "الْقُدُّوسُ",
    translation: "The Absolutely Pure and Perfect",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n05",
    title: "As-Salām",
    arabic: "السَّلاَمُ",
    translation: "The Source of Peace, The Flawless",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n06",
    title: "Al-Muʾmin",
    arabic: "الْمُؤْمِنُ",
    translation: "The Granter of Security and Faith",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n07",
    title: "Al-Muhaymin",
    arabic: "الْمُهَيْمِنُ",
    translation: "The Guardian, The Witness, The Overseer",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n08",
    title: "Al-ʿAzīz",
    arabic: "الْعَزِيزُ",
    translation: "The Almighty, The All-Powerful, The Invincible",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n09",
    title: "Al-Jabbār",
    arabic: "الْجَبَّارُ",
    translation: "The Compeller, The Restorer",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n10",
    title: "Al-Mutakabbir",
    arabic: "الْمُتَكَبِّرُ",
    translation: "The Supreme in Glory, The Rightfully Proud",
    note: "Qur’an 59:23",
    sources: [quran(59, 23, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n11",
    title: "Al-Khāliq",
    arabic: "الْخَالِقُ",
    translation: "The Creator, The Maker",
    note: "Qur’an 59:24",
    sources: [quran(59, 24, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n12",
    title: "Al-Bāriʾ",
    arabic: "الْبَارِئُ",
    translation: "The Originator, The Inventor",
    note: "Qur’an 59:24",
    sources: [quran(59, 24, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n13",
    title: "Al-Muṣawwir",
    arabic: "الْمُصَوِّرُ",
    translation: "The Fashioner, The Shaper",
    note: "Qur’an 59:24",
    sources: [quran(59, 24, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n14",
    title: "Al-Ghaffār",
    arabic: "الْغَفَّارُ",
    translation: "The Constant Forgiver, The Great Forgiver",
  },
  {
    id: "n15",
    title: "Al-Qahhār",
    arabic: "الْقَهَّارُ",
    translation: "The Subduer, The Ever-Dominating",
  },
  {
    id: "n16",
    title: "Al-Wahhāb",
    arabic: "الْوَهَّابُ",
    translation: "The Giver of Gifts, The Bestower",
  },
  {
    id: "n17",
    title: "Ar-Razzāq",
    arabic: "الرَّزَّاقُ",
    translation: "The Ever-Providing, The Constant Provider",
  },
  {
    id: "n18",
    title: "Al-Fattāḥ",
    arabic: "الْفَتَّاحُ",
    translation: "The Opener, The Judge",
  },
  {
    id: "n19",
    title: "Al-ʿAlīm",
    arabic: "اَلْعَلِيْمُ",
    translation: "The All-Knowing, The Omniscient",
  },
  {
    id: "n20",
    title: "Al-Qābiḍ",
    arabic: "الْقَابِضُ",
    translation: "The Withholder, The Restrainer",
  },
  {
    id: "n21",
    title: "Al-Bāsiṭ",
    arabic: "الْبَاسِطُ",
    translation: "The Extender, The Expander",
  },
  {
    id: "n22",
    title: "Al-Khāfiḍ",
    arabic: "الْخَافِضُ",
    translation: "The Reducer, The Abaser",
  },
  {
    id: "n23",
    title: "Ar-Rāfiʿ",
    arabic: "الرَّافِعُ",
    translation: "The Exalter, The Elevator",
  },
  {
    id: "n24",
    title: "Al-Muʿizz",
    arabic: "الْمُعِزُّ",
    translation: "The Honourer, The Bestower of Honor",
  },
  {
    id: "n25",
    title: "Al-Mudhil",
    arabic: "المُذِلُّ",
    translation: "The Dishonourer, The Humiliator",
  },
  {
    id: "n26",
    title: "As-Samīʿ",
    arabic: "السَّمِيعُ",
    translation: "The All-Hearing",
  },
  {
    id: "n27",
    title: "Al-Baṣīr",
    arabic: "الْبَصِيرُ",
    translation: "The All-Seeing",
  },
  {
    id: "n28",
    title: "Al-Ḥakam",
    arabic: "الْحَكَمُ",
    translation: "The Judge, The Giver of Justice",
  },
  {
    id: "n29",
    title: "Al-ʿAdl",
    arabic: "الْعَدْلُ",
    translation: "The Utterly Just",
  },
  {
    id: "n30",
    title: "Al-Laṭīf",
    arabic: "اللَّطِيفُ",
    translation: "The Most Gentle, The Subtle One",
  },
  {
    id: "n31",
    title: "Al-Khabīr",
    arabic: "الْخَبِيرُ",
    translation: "The All-Aware, The All-Acquainted",
  },
  {
    id: "n32",
    title: "Al-Ḥalīm",
    arabic: "الْحَلِيمُ",
    translation: "The Most Forbearing",
  },
  {
    id: "n33",
    title: "Al-ʿAẓīm",
    arabic: "الْعَظِيمُ",
    translation: "The Magnificent, The Supreme",
  },
  {
    id: "n34",
    title: "Al-Ghafūr",
    arabic: "الْغَفُورُ",
    translation: "The Forgiving, The Exceedingly Forgiving",
  },
  {
    id: "n35",
    title: "Ash-Shakūr",
    arabic: "الشَّكُورُ",
    translation: "The Most Appreciative",
  },
  {
    id: "n36",
    title: "Al-ʿAlī",
    arabic: "الْعَلِيُّ",
    translation: "The Most High, The Exalted",
  },
  {
    id: "n37",
    title: "Al-Kabīr",
    arabic: "الْكَبِيرُ",
    translation: "The Greatest, The Most Grand",
  },
  {
    id: "n38",
    title: "Al-Ḥafīẓ",
    arabic: "الْحَفِيظُ",
    translation: "The Preserver, The All-Heedful and All-Protecting",
  },
  {
    id: "n39",
    title: "Al-Muqīt",
    arabic: "المُقيِت",
    translation: "The Nourisher, The All-Powerful Maintainer",
  },
  {
    id: "n40",
    title: "Al-Ḥasīb",
    arabic: "الْحسِيبُ",
    translation: "The Reckoner",
  },
  {
    id: "n41",
    title: "Al-Jalīl",
    arabic: "الْجَلِيلُ",
    translation: "The Majestic",
  },
  {
    id: "n42",
    title: "Al-Karīm",
    arabic: "الْكَرِيمُ",
    translation: "The Most Generous, The Most Noble",
  },
  {
    id: "n43",
    title: "Ar-Raqīb",
    arabic: "الرَّقِيبُ",
    translation: "The Watchful, The All-Watchful",
  },
  {
    id: "n44",
    title: "Al-Mujīb",
    arabic: "الْمُجِيبُ",
    translation: "The Responsive, The Answerer",
  },
  {
    id: "n45",
    title: "Al-Wāsiʿ",
    arabic: "الْوَاسِعُ",
    translation: "The All-Encompassing, The Boundless",
  },
  {
    id: "n46",
    title: "Al-Ḥakīm",
    arabic: "الْحَكِيمُ",
    translation: "The All-Wise",
    note: "Qur’an 59:24",
    sources: [quran(59, 24, { surahName: 'Al-Hashr' })],
  },
  {
    id: "n47",
    title: "Al-Wadūd",
    arabic: "الْوَدُودُ",
    translation: "The Most Loving",
  },
  {
    id: "n48",
    title: "Al-Majīd",
    arabic: "الْمَجِيدُ",
    translation: "The All-Glorious, The Ever-Majestic",
  },
  {
    id: "n49",
    title: "Al-Bāʿith",
    arabic: "الْبَاعِثُ",
    translation: "The Infuser of New Life, The Resurrector",
  },
  {
    id: "n50",
    title: "Ash-Shahīd",
    arabic: "الشَّهِيدُ",
    translation: "The All-Witnessing",
  },
  {
    id: "n51",
    title: "Al-Ḥaqq",
    arabic: "الْحَقُّ",
    translation: "The Absolute Truth",
  },
  {
    id: "n52",
    title: "Al-Wakīl",
    arabic: "الْوَكِيلُ",
    translation: "The Trustee, The Disposer of Affairs",
  },
  {
    id: "n53",
    title: "Al-Qawiyy",
    arabic: "الْقَوِيُّ",
    translation: "The All-Strong",
  },
  {
    id: "n54",
    title: "Al-Matīn",
    arabic: "الْمَتِينُ",
    translation: "The Firm, The Steadfast",
  },
  {
    id: "n55",
    title: "Al-Waliyy",
    arabic: "الْوَلِيُّ",
    translation: "The Protector, The Guardian",
  },
  {
    id: "n56",
    title: "Al-Ḥamīd",
    arabic: "الْحَمِيدُ",
    translation: "The Praiseworthy, The Most Praised",
  },
  {
    id: "n57",
    title: "Al-Muḥṣī",
    arabic: "الْمُحْصِي",
    translation: "The All-Enumerating, The Counter",
  },
  {
    id: "n58",
    title: "Al-Mubdiʾ",
    arabic: "الْمُبْدِئُ",
    translation: "The Originator, The Initiator",
  },
  {
    id: "n59",
    title: "Al-Muʿīd",
    arabic: "الْمُعِيدُ",
    translation: "The Restorer, The Reviver",
  },
  {
    id: "n60",
    title: "Al-Muḥyī",
    arabic: "الْمُحْيِي",
    translation: "The Giver of Life",
  },
  {
    id: "n61",
    title: "Al-Mumīt",
    arabic: "اَلْمُمِيتُ",
    translation: "The Taker of Life, The Causer of Death",
  },
  {
    id: "n62",
    title: "Al-Ḥayy",
    arabic: "الْحَيُّ",
    translation: "The Ever-Living",
  },
  {
    id: "n63",
    title: "Al-Qayyūm",
    arabic: "الْقَيُّومُ",
    translation: "The Sustainer, The Self-Subsisting",
  },
  {
    id: "n64",
    title: "Al-Wājid",
    arabic: "الْوَاجِدُ",
    translation: "The Ever-Wealthy, The Self-Sufficient",
  },
  {
    id: "n65",
    title: "Al-Mājid",
    arabic: "الْمَاجِدُ",
    translation: "The Noble, The Generous",
  },
  {
    id: "n66",
    title: "Al-Wāḥid",
    arabic: "الْواحِدُ",
    translation: "The One, The Indivisible",
  },
  {
    id: "n67",
    title: "Al-Aḥad",
    arabic: "اَلاَحَدُ",
    translation: "The Unique, The Only One",
  },
  {
    id: "n68",
    title: "Aṣ-Ṣamad",
    arabic: "الصَّمَدُ",
    translation: "The Self-Subsisting, The One Upon Whom All Depend",
  },
  {
    id: "n69",
    title: "Al-Qādir",
    arabic: "الْقَادِرُ",
    translation: "The Omnipotent, The All-Able",
  },
  {
    id: "n70",
    title: "Al-Muqtadir",
    arabic: "الْمُقْتَدِرُ",
    translation: "The All-Powerful, The Dominant",
  },
  {
    id: "n71",
    title: "Al-Muqaddim",
    arabic: "الْمُقَدِّمُ",
    translation: "The Expediter, The Promoter",
  },
  {
    id: "n72",
    title: "Al-Muʾakhkhir",
    arabic: "الْمُؤَخِّرُ",
    translation: "The Delayer, The Postponer",
  },
  {
    id: "n73",
    title: "Al-Awwal",
    arabic: "الأوَّلُ",
    translation: "The First, The Pre-Existing",
  },
  {
    id: "n74",
    title: "Al-Ākhir",
    arabic: "الآخِرُ",
    translation: "The Last, The Ever-Remaining",
  },
  {
    id: "n75",
    title: "Aẓ-Ẓāhir",
    arabic: "الظَّاهِرُ",
    translation: "The Manifest, The Highest",
  },
  {
    id: "n76",
    title: "Al-Bāṭin",
    arabic: "الْبَاطِنُ",
    translation: "The Hidden One, Knower of the Hidden",
  },
  {
    id: "n77",
    title: "Al-Wālī",
    arabic: "الْوَالِي",
    translation: "The Sole Governor",
  },
  {
    id: "n78",
    title: "Al-Mutaʿālī",
    arabic: "الْمُتَعَالِي",
    translation: "The Self-Exalted",
  },
  {
    id: "n79",
    title: "Al-Barr",
    arabic: "الْبَرُّ",
    translation: "The Source of All Goodness",
  },
  {
    id: "n80",
    title: "At-Tawwāb",
    arabic: "التَّوَابُ",
    translation: "The Accepter of Repentance, The Ever-Relenting",
  },
  {
    id: "n81",
    title: "Al-Muntaqim",
    arabic: "الْمُنْتَقِمُ",
    translation: "The Avenger",
  },
  {
    id: "n82",
    title: "Al-ʿAfūw",
    arabic: "العَفُوُّ",
    translation: "The Pardoner",
  },
  {
    id: "n83",
    title: "Ar-Raʾūf",
    arabic: "الرَّؤُوفُ",
    translation: "The Most Kind",
  },
  {
    id: "n84",
    title: "Mālik al-Mulk",
    arabic: "مَالِكُ الْمُلْكِ",
    translation: "Master of the Dominion, Owner of the Kingdom",
  },
  {
    id: "n85",
    title: "Dhū al-Jalāli wa-l-Ikrām",
    arabic: "ذُوالْجَلاَلِ وَالإكْرَامِ",
    translation: "Possessor of Glory and Honour",
  },
  {
    id: "n86",
    title: "Al-Muqsiṭ",
    arabic: "الْمُقْسِطُ",
    translation: "The Just One",
  },
  {
    id: "n87",
    title: "Al-Jāmiʿ",
    arabic: "الْجَامِعُ",
    translation: "The Gatherer, The Uniter",
  },
  {
    id: "n88",
    title: "Al-Ghaniyy",
    arabic: "الْغَنِيُّ",
    translation: "The Self-Sufficient, The Free of All Need",
  },
  {
    id: "n89",
    title: "Al-Mughnī",
    arabic: "الْمُغْنِي",
    translation: "The Enricher",
  },
  {
    id: "n90",
    title: "Al-Māniʿ",
    arabic: "اَلْمَانِعُ",
    translation: "The Withholder",
  },
  {
    id: "n91",
    title: "Aḍ-Ḍārr",
    arabic: "الضَّارَّ",
    translation: "The Creator of Harm",
  },
  {
    id: "n92",
    title: "An-Nāfiʿ",
    arabic: "النَّافِعُ",
    translation: "The Propitious, The Benefactor",
  },
  {
    id: "n93",
    title: "An-Nūr",
    arabic: "النُّورُ",
    translation: "The Light",
  },
  {
    id: "n94",
    title: "Al-Hādī",
    arabic: "الْهَادِي",
    translation: "The Guide",
  },
  {
    id: "n95",
    title: "Al-Badīʿ",
    arabic: "الْبَدِيعُ",
    translation: "The Incomparable Originator",
  },
  {
    id: "n96",
    title: "Al-Bāqī",
    arabic: "اَلْبَاقِي",
    translation: "The Ever-Lasting",
  },
  {
    id: "n97",
    title: "Al-Wāriṯ",
    arabic: "الْوَارِثُ",
    translation: "The Inheritor",
  },
  {
    id: "n98",
    title: "Ar-Rashīd",
    arabic: "الرَّشِيدُ",
    translation: "The Guide to the Right Path",
  },
  {
    id: "n99",
    title: "Aṣ-Ṣabūr",
    arabic: "الصَّبُورُ",
    translation: "The Patient",
  },
  ],
};
