/**
 * The duʿas the Qur'an puts in people's mouths.
 *
 * GENERATED by `npm run collection:duas`. Do not edit by hand.
 *
 * Every character — Arabic and English — came over the wire from QuranEnc's
 * Saheeh International edition, and both come from the SAME verse, so they
 * cannot drift apart. No text is sliced: the whole ayah ships, framing and
 * all, because deciding where a supplication begins would be an editorial act
 * on a Qur'an text, and the framing is what tells a reader whose words these
 * are.
 *
 * ⚠️ The references are stated rather than found by a rule. Searching all
 * 6,236 ayahs for the vocative returns 215 verses, the first of which is 1:2 —
 * "Lord of the worlds", a description rather than an address. See the
 * generator's header.
 *
 * ⚠️ Hisn al-Muslim, already in this app, is hadith-centred. This is the body
 * of supplication it does not carry.
 */
import { quran } from '../sources';
import type { Collection } from '../types';

export const QURANIC_DUAS: Collection = {
  id: 'quranic-duas',
  title: 'Duʿas from the Qur’an',
  subtitle: 'The words the Qur’an gives to the prophets, and to everyone after them.',
  provider: 'quranenc',
  meta: {
    category: 'quran',
    difficulty: 'building',
    estimatedMinutes: 15,
    beginnerPriority: 3,
    tags: ['arabic'],
    relatedContent: [{ kind: 'reference', id: 'dua-and-dhikr' }],
  },
  entries: [
  {
    id: "adam",
    title: "Ādam — After the mistake",
    arabic: "قَالَا رَبَّنَا ظَلَمۡنَآ أَنفُسَنَا وَإِن لَّمۡ تَغۡفِرۡ لَنَا وَتَرۡحَمۡنَا لَنَكُونَنَّ مِنَ ٱلۡخَٰسِرِينَ",
    translation: "They said, \"Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.\"",
    note: "Qur’an 7:23",
    sources: [quran(7, 23)],
  },
  {
    id: "nuh",
    title: "Nūḥ — For his parents and the believers",
    arabic: "رَّبِّ ٱغۡفِرۡ لِي وَلِوَٰلِدَيَّ وَلِمَن دَخَلَ بَيۡتِيَ مُؤۡمِنٗا وَلِلۡمُؤۡمِنِينَ وَٱلۡمُؤۡمِنَٰتِۖ وَلَا تَزِدِ ٱلظَّٰلِمِينَ إِلَّا تَبَارَۢا",
    translation: "My Lord, forgive me and my parents and whoever enters my house a believer and the believing men and believing women. And do not increase the wrongdoers except in destruction.\"",
    note: "Qur’an 71:28",
    sources: [quran(71, 28)],
  },
  {
    id: "ibrahim-city",
    title: "Ibrāhīm — For a safe city",
    arabic: "وَإِذۡ قَالَ إِبۡرَٰهِـۧمُ رَبِّ ٱجۡعَلۡ هَٰذَا بَلَدًا ءَامِنٗا وَٱرۡزُقۡ أَهۡلَهُۥ مِنَ ٱلثَّمَرَٰتِ مَنۡ ءَامَنَ مِنۡهُم بِٱللَّهِ وَٱلۡيَوۡمِ ٱلۡأٓخِرِۚ قَالَ وَمَن كَفَرَ فَأُمَتِّعُهُۥ قَلِيلٗا ثُمَّ أَضۡطَرُّهُۥٓ إِلَىٰ عَذَابِ ٱلنَّارِۖ وَبِئۡسَ ٱلۡمَصِيرُ",
    translation: "And [mention] when Abraham said, \"My Lord, make this a secure city and provide its people with fruits - whoever of them believes in Allāh and the Last Day.\" [Allāh] said, \"And whoever disbelieves - I will grant him enjoyment for a little; then I will force him to the punishment of the Fire, and wretched is the destination.\"",
    note: "Qur’an 2:126",
    sources: [quran(2, 126)],
  },
  {
    id: "ibrahim-accept",
    title: "Ibrāhīm — Building the House",
    arabic: "وَإِذۡ يَرۡفَعُ إِبۡرَٰهِـۧمُ ٱلۡقَوَاعِدَ مِنَ ٱلۡبَيۡتِ وَإِسۡمَٰعِيلُ رَبَّنَا تَقَبَّلۡ مِنَّآۖ إِنَّكَ أَنتَ ٱلسَّمِيعُ ٱلۡعَلِيمُ",
    translation: "And [mention] when Abraham was raising the foundations of the House and [with him] Ishmael, [saying], \"Our Lord, accept [this] from us. Indeed, You are the Hearing, the Knowing.",
    note: "Qur’an 2:127",
    sources: [quran(2, 127)],
  },
  {
    id: "ibrahim-muslims",
    title: "Ibrāhīm — For his descendants",
    arabic: "رَبَّنَا وَٱجۡعَلۡنَا مُسۡلِمَيۡنِ لَكَ وَمِن ذُرِّيَّتِنَآ أُمَّةٗ مُّسۡلِمَةٗ لَّكَ وَأَرِنَا مَنَاسِكَنَا وَتُبۡ عَلَيۡنَآۖ إِنَّكَ أَنتَ ٱلتَّوَّابُ ٱلرَّحِيمُ",
    translation: "Our Lord, and make us Muslims [in submission] to You and from our descendants a Muslim nation [in submission] to You. And show us our rites [of worship] and accept our repentance. Indeed, You are the Accepting of Repentance, the Merciful.",
    note: "Qur’an 2:128",
    sources: [quran(2, 128)],
  },
  {
    id: "ibrahim-prayer",
    title: "Ibrāhīm — To be kept in prayer",
    arabic: "رَبِّ ٱجۡعَلۡنِي مُقِيمَ ٱلصَّلَوٰةِ وَمِن ذُرِّيَّتِيۚ رَبَّنَا وَتَقَبَّلۡ دُعَآءِ",
    translation: "My Lord, make me an establisher of prayer, and [many] from my descendants. Our Lord, and accept my supplication.",
    note: "Qur’an 14:40",
    sources: [quran(14, 40)],
  },
  {
    id: "ibrahim-forgive",
    title: "Ibrāhīm — For his parents",
    arabic: "رَبَّنَا ٱغۡفِرۡ لِي وَلِوَٰلِدَيَّ وَلِلۡمُؤۡمِنِينَ يَوۡمَ يَقُومُ ٱلۡحِسَابُ",
    translation: "Our Lord, forgive me and my parents and the believers the Day the account is established.\"",
    note: "Qur’an 14:41",
    sources: [quran(14, 41)],
  },
  {
    id: "ibrahim-wisdom",
    title: "Ibrāhīm — For wisdom and good company",
    arabic: "رَبِّ هَبۡ لِي حُكۡمٗا وَأَلۡحِقۡنِي بِٱلصَّٰلِحِينَ",
    translation: "[And he said], \"My Lord, grant me authority and join me with the righteous.",
    note: "Qur’an 26:83",
    sources: [quran(26, 83)],
  },
  {
    id: "yusuf",
    title: "Yūsuf — At the end of the story",
    arabic: "۞ رَبِّ قَدۡ ءَاتَيۡتَنِي مِنَ ٱلۡمُلۡكِ وَعَلَّمۡتَنِي مِن تَأۡوِيلِ ٱلۡأَحَادِيثِۚ فَاطِرَ ٱلسَّمَٰوَٰتِ وَٱلۡأَرۡضِ أَنتَ وَلِيِّۦ فِي ٱلدُّنۡيَا وَٱلۡأٓخِرَةِۖ تَوَفَّنِي مُسۡلِمٗا وَأَلۡحِقۡنِي بِٱلصَّٰلِحِينَ",
    translation: "My Lord, You have given me [something] of sovereignty and taught me of the interpretation of dreams. Creator of the heavens and earth, You are my protector in this world and the Hereafter. Cause me to die a Muslim and join me with the righteous.\"",
    note: "Qur’an 12:101",
    sources: [quran(12, 101)],
  },
  {
    id: "musa-chest",
    title: "Mūsā — Before speaking to Pharaoh",
    arabic: "قَالَ رَبِّ ٱشۡرَحۡ لِي صَدۡرِي",
    translation: "[Moses] said, \"My Lord, expand [i.e., relax] for me my breast [with assurance]",
    note: "Qur’an 20:25",
    sources: [quran(20, 25)],
  },
  {
    id: "musa-task",
    title: "Mūsā — Make my task easy",
    arabic: "وَيَسِّرۡ لِيٓ أَمۡرِي",
    translation: "And ease for me my task",
    note: "Qur’an 20:26",
    sources: [quran(20, 26)],
  },
  {
    id: "musa-tongue",
    title: "Mūsā — Untie the knot from my tongue",
    arabic: "وَٱحۡلُلۡ عُقۡدَةٗ مِّن لِّسَانِي",
    translation: "And untie the knot from my tongue",
    note: "Qur’an 20:27",
    sources: [quran(20, 27)],
  },
  {
    id: "musa-poor",
    title: "Mūsā — Alone and with nothing",
    arabic: "فَسَقَىٰ لَهُمَا ثُمَّ تَوَلَّىٰٓ إِلَى ٱلظِّلِّ فَقَالَ رَبِّ إِنِّي لِمَآ أَنزَلۡتَ إِلَيَّ مِنۡ خَيۡرٖ فَقِيرٞ",
    translation: "So he watered [their flocks] for them; then he went back to the shade and said, \"My Lord, indeed I am, for whatever good You would send down to me, in need.\"",
    note: "Qur’an 28:24",
    sources: [quran(28, 24)],
  },
  {
    id: "musa-forgive",
    title: "Mūsā — For himself and his brother",
    arabic: "قَالَ رَبِّ ٱغۡفِرۡ لِي وَلِأَخِي وَأَدۡخِلۡنَا فِي رَحۡمَتِكَۖ وَأَنتَ أَرۡحَمُ ٱلرَّٰحِمِينَ",
    translation: "[Moses] said, \"My Lord, forgive me and my brother and admit us into Your mercy, for You are the most merciful of the merciful.\"",
    note: "Qur’an 7:151",
    sources: [quran(7, 151)],
  },
  {
    id: "zakariyya-offspring",
    title: "Zakariyyā — For a child",
    arabic: "هُنَالِكَ دَعَا زَكَرِيَّا رَبَّهُۥۖ قَالَ رَبِّ هَبۡ لِي مِن لَّدُنكَ ذُرِّيَّةٗ طَيِّبَةًۖ إِنَّكَ سَمِيعُ ٱلدُّعَآءِ",
    translation: "At that, Zechariah called upon his Lord, saying, \"My Lord, grant me from Yourself a good offspring. Indeed, You are the Hearer of supplication.\"",
    note: "Qur’an 3:38",
    sources: [quran(3, 38)],
  },
  {
    id: "zakariyya-alone",
    title: "Zakariyyā — Do not leave me alone",
    arabic: "وَزَكَرِيَّآ إِذۡ نَادَىٰ رَبَّهُۥ رَبِّ لَا تَذَرۡنِي فَرۡدٗا وَأَنتَ خَيۡرُ ٱلۡوَٰرِثِينَ",
    translation: "And [mention] Zechariah, when he called to his Lord, \"My Lord, do not leave me alone [with no heir], while You are the best of inheritors.\"",
    note: "Qur’an 21:89",
    sources: [quran(21, 89)],
  },
  {
    id: "ayyub",
    title: "Ayyūb — In illness",
    arabic: "۞ وَأَيُّوبَ إِذۡ نَادَىٰ رَبَّهُۥٓ أَنِّي مَسَّنِيَ ٱلضُّرُّ وَأَنتَ أَرۡحَمُ ٱلرَّٰحِمِينَ",
    translation: "And [mention] Job, when he called to his Lord, \"Indeed, adversity has touched me, and You are the most merciful of the merciful.\"",
    note: "Qur’an 21:83",
    sources: [quran(21, 83)],
  },
  {
    id: "yunus",
    title: "Yūnus — From inside the darkness",
    arabic: "وَذَا ٱلنُّونِ إِذ ذَّهَبَ مُغَٰضِبٗا فَظَنَّ أَن لَّن نَّقۡدِرَ عَلَيۡهِ فَنَادَىٰ فِي ٱلظُّلُمَٰتِ أَن لَّآ إِلَٰهَ إِلَّآ أَنتَ سُبۡحَٰنَكَ إِنِّي كُنتُ مِنَ ٱلظَّٰلِمِينَ",
    translation: "And [mention] the man of the fish [i.e., Jonah], when he went off in anger and thought that We would not decree [anything] upon him. And he called out within the darknesses, \"There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.\"",
    note: "Qur’an 21:87",
    sources: [quran(21, 87)],
  },
  {
    id: "sulayman-gratitude",
    title: "Sulaymān — To be grateful",
    arabic: "فَتَبَسَّمَ ضَاحِكٗا مِّن قَوۡلِهَا وَقَالَ رَبِّ أَوۡزِعۡنِيٓ أَنۡ أَشۡكُرَ نِعۡمَتَكَ ٱلَّتِيٓ أَنۡعَمۡتَ عَلَيَّ وَعَلَىٰ وَٰلِدَيَّ وَأَنۡ أَعۡمَلَ صَٰلِحٗا تَرۡضَىٰهُ وَأَدۡخِلۡنِي بِرَحۡمَتِكَ فِي عِبَادِكَ ٱلصَّٰلِحِينَ",
    translation: "So [Solomon] smiled, amused at her speech, and said, \"My Lord, enable me to be grateful for Your favor which You have bestowed upon me and upon my parents and to do righteousness of which You approve. And admit me by Your mercy into [the ranks of] Your righteous servants.\"",
    note: "Qur’an 27:19",
    sources: [quran(27, 19)],
  },
  {
    id: "lut",
    title: "Lūṭ — To be saved from what people do",
    arabic: "رَبِّ نَجِّنِي وَأَهۡلِي مِمَّا يَعۡمَلُونَ",
    translation: "My Lord, save me and my family from [the consequence of] what they do.\"",
    note: "Qur’an 26:169",
    sources: [quran(26, 169)],
  },
  {
    id: "shuayb",
    title: "Shuʿayb — For a just decision",
    arabic: "قَدِ ٱفۡتَرَيۡنَا عَلَى ٱللَّهِ كَذِبًا إِنۡ عُدۡنَا فِي مِلَّتِكُم بَعۡدَ إِذۡ نَجَّىٰنَا ٱللَّهُ مِنۡهَاۚ وَمَا يَكُونُ لَنَآ أَن نَّعُودَ فِيهَآ إِلَّآ أَن يَشَآءَ ٱللَّهُ رَبُّنَاۚ وَسِعَ رَبُّنَا كُلَّ شَيۡءٍ عِلۡمًاۚ عَلَى ٱللَّهِ تَوَكَّلۡنَاۚ رَبَّنَا ٱفۡتَحۡ بَيۡنَنَا وَبَيۡنَ قَوۡمِنَا بِٱلۡحَقِّ وَأَنتَ خَيۡرُ ٱلۡفَٰتِحِينَ",
    translation: "We would have invented against Allāh a lie if we returned to your religion after Allāh had saved us from it. And it is not for us to return to it except that Allāh, our Lord, should will. Our Lord has encompassed all things in knowledge. Upon Allāh we have relied. Our Lord, decide between us and our people in truth, and You are the best of those who give decision.\"",
    note: "Qur’an 7:89",
    sources: [quran(7, 89)],
  },
  {
    id: "maryam-mother",
    title: "The mother of Maryam — Dedicating her child",
    arabic: "إِذۡ قَالَتِ ٱمۡرَأَتُ عِمۡرَٰنَ رَبِّ إِنِّي نَذَرۡتُ لَكَ مَا فِي بَطۡنِي مُحَرَّرٗا فَتَقَبَّلۡ مِنِّيٓۖ إِنَّكَ أَنتَ ٱلسَّمِيعُ ٱلۡعَلِيمُ",
    translation: "[Mention, O Muḥammad], when the wife of ʿImrān said, \"My Lord, indeed I have pledged to You what is in my womb, consecrated [for Your service], so accept this from me. Indeed, You are the Hearing, the Knowing.\"",
    note: "Qur’an 3:35",
    sources: [quran(3, 35)],
  },
  {
    id: "asiyah",
    title: "The wife of Pharaoh — For a house in Paradise",
    arabic: "وَضَرَبَ ٱللَّهُ مَثَلٗا لِّلَّذِينَ ءَامَنُواْ ٱمۡرَأَتَ فِرۡعَوۡنَ إِذۡ قَالَتۡ رَبِّ ٱبۡنِ لِي عِندَكَ بَيۡتٗا فِي ٱلۡجَنَّةِ وَنَجِّنِي مِن فِرۡعَوۡنَ وَعَمَلِهِۦ وَنَجِّنِي مِنَ ٱلۡقَوۡمِ ٱلظَّٰلِمِينَ",
    translation: "And Allāh presents an example of those who believed: the wife of Pharaoh, when she said, \"My Lord, build for me near You a house in Paradise and save me from Pharaoh and his deeds and save me from the wrongdoing people.\"",
    note: "Qur’an 66:11",
    sources: [quran(66, 11)],
  },
  {
    id: "muhammad-knowledge",
    title: "The Prophet ﷺ — Increase me in knowledge",
    arabic: "فَتَعَٰلَى ٱللَّهُ ٱلۡمَلِكُ ٱلۡحَقُّۗ وَلَا تَعۡجَلۡ بِٱلۡقُرۡءَانِ مِن قَبۡلِ أَن يُقۡضَىٰٓ إِلَيۡكَ وَحۡيُهُۥۖ وَقُل رَّبِّ زِدۡنِي عِلۡمٗا",
    translation: "So high [above all] is Allāh, the Sovereign, the Truth. And, [O Muḥammad], do not hasten with [recitation of] the Qur’ān before its revelation is completed to you, and say, \"My Lord, increase me in knowledge.\"",
    note: "Qur’an 20:114",
    sources: [quran(20, 114)],
  },
  {
    id: "muhammad-mercy",
    title: "The Prophet ﷺ — Forgive and have mercy",
    arabic: "وَقُل رَّبِّ ٱغۡفِرۡ وَٱرۡحَمۡ وَأَنتَ خَيۡرُ ٱلرَّٰحِمِينَ",
    translation: "And, [O Muḥammad], say, \"My Lord, forgive and have mercy, and You are the best of the merciful.\"",
    note: "Qur’an 23:118",
    sources: [quran(23, 118)],
  },
  {
    id: "believers-both",
    title: "The believers — Good in both lives",
    arabic: "وَمِنۡهُم مَّن يَقُولُ رَبَّنَآ ءَاتِنَا فِي ٱلدُّنۡيَا حَسَنَةٗ وَفِي ٱلۡأٓخِرَةِ حَسَنَةٗ وَقِنَا عَذَابَ ٱلنَّارِ",
    translation: "But among them is he who says, \"Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.\"",
    note: "Qur’an 2:201",
    sources: [quran(2, 201)],
  },
  {
    id: "believers-burden",
    title: "The believers — Do not burden us",
    arabic: "لَا يُكَلِّفُ ٱللَّهُ نَفۡسًا إِلَّا وُسۡعَهَاۚ لَهَا مَا كَسَبَتۡ وَعَلَيۡهَا مَا ٱكۡتَسَبَتۡۗ رَبَّنَا لَا تُؤَاخِذۡنَآ إِن نَّسِينَآ أَوۡ أَخۡطَأۡنَاۚ رَبَّنَا وَلَا تَحۡمِلۡ عَلَيۡنَآ إِصۡرٗا كَمَا حَمَلۡتَهُۥ عَلَى ٱلَّذِينَ مِن قَبۡلِنَاۚ رَبَّنَا وَلَا تُحَمِّلۡنَا مَا لَا طَاقَةَ لَنَا بِهِۦۖ وَٱعۡفُ عَنَّا وَٱغۡفِرۡ لَنَا وَٱرۡحَمۡنَآۚ أَنتَ مَوۡلَىٰنَا فَٱنصُرۡنَا عَلَى ٱلۡقَوۡمِ ٱلۡكَٰفِرِينَ",
    translation: "Allāh does not charge a soul except [with that within] its capacity. It will have [the consequence of] what [good] it has gained, and it will bear [the consequence of] what [evil] it has earned. \"Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us. Our Lord, and burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us. You are our protector, so give us victory over the disbelieving people.\"",
    note: "Qur’an 2:286",
    sources: [quran(2, 286)],
  },
  {
    id: "believers-hearts",
    title: "The believers — Do not let our hearts deviate",
    arabic: "رَبَّنَا لَا تُزِغۡ قُلُوبَنَا بَعۡدَ إِذۡ هَدَيۡتَنَا وَهَبۡ لَنَا مِن لَّدُنكَ رَحۡمَةًۚ إِنَّكَ أَنتَ ٱلۡوَهَّابُ",
    translation: "[Who say], \"Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.",
    note: "Qur’an 3:8",
    sources: [quran(3, 8)],
  },
  {
    id: "believers-patience",
    title: "The believers — For steadfastness",
    arabic: "وَمَا كَانَ قَوۡلَهُمۡ إِلَّآ أَن قَالُواْ رَبَّنَا ٱغۡفِرۡ لَنَا ذُنُوبَنَا وَإِسۡرَافَنَا فِيٓ أَمۡرِنَا وَثَبِّتۡ أَقۡدَامَنَا وَٱنصُرۡنَا عَلَى ٱلۡقَوۡمِ ٱلۡكَٰفِرِينَ",
    translation: "And their words were not but that they said, \"Our Lord, forgive us our sins and the excess [committed] in our affairs and plant firmly our feet and give us victory over the disbelieving people.\"",
    note: "Qur’an 3:147",
    sources: [quran(3, 147)],
  },
  {
    id: "cave",
    title: "The young men of the cave — Taking shelter",
    arabic: "إِذۡ أَوَى ٱلۡفِتۡيَةُ إِلَى ٱلۡكَهۡفِ فَقَالُواْ رَبَّنَآ ءَاتِنَا مِن لَّدُنكَ رَحۡمَةٗ وَهَيِّئۡ لَنَا مِنۡ أَمۡرِنَا رَشَدٗا",
    translation: "[Mention] when the youths retreated to the cave and said, \"Our Lord, grant us from Yourself mercy and prepare for us from our affair right guidance.\"",
    note: "Qur’an 18:10",
    sources: [quran(18, 10)],
  },
  {
    id: "servants",
    title: "The servants of the Most Merciful — For family",
    arabic: "وَٱلَّذِينَ يَقُولُونَ رَبَّنَا هَبۡ لَنَا مِنۡ أَزۡوَٰجِنَا وَذُرِّيَّٰتِنَا قُرَّةَ أَعۡيُنٖ وَٱجۡعَلۡنَا لِلۡمُتَّقِينَ إِمَامًا",
    translation: "And those who say, \"Our Lord, grant us from among our wives and offspring comfort to our eyes and make us a leader [i.e., example] for the righteous.\"",
    note: "Qur’an 25:74",
    sources: [quran(25, 74)],
  },
  {
    id: "later-believers",
    title: "Those who came after — For those before us",
    arabic: "وَٱلَّذِينَ جَآءُو مِنۢ بَعۡدِهِمۡ يَقُولُونَ رَبَّنَا ٱغۡفِرۡ لَنَا وَلِإِخۡوَٰنِنَا ٱلَّذِينَ سَبَقُونَا بِٱلۡإِيمَٰنِ وَلَا تَجۡعَلۡ فِي قُلُوبِنَا غِلّٗا لِّلَّذِينَ ءَامَنُواْ رَبَّنَآ إِنَّكَ رَءُوفٞ رَّحِيمٌ",
    translation: "And [there is a share for] those who come after them, saying, \"Our Lord, forgive us and our brothers who preceded us in faith and put not in our hearts [any] resentment toward those who have believed. Our Lord, indeed You are Kind and Merciful.\"",
    note: "Qur’an 59:10",
    sources: [quran(59, 10)],
  },
  ],
};
