/**
 * What gold and silver cost, on the day this was last built.
 *
 * GENERATED by `npm run zakat:nisab`. Do not edit by hand.
 *
 * ⚠️ This is a SNAPSHOT and the screen must say so. The price moves daily and
 * this file does not; it refreshes when an OTA ships. A zakat figure presented
 * without its date is a figure somebody will act on months after it stopped
 * being true.
 *
 * The gram thresholds below are NOT from this API and not from any hadith. The
 * hadith give 20 dinars and 200 dirhams — Abu Dawud 1573, and Bukhari 1447 for
 * the five awāq of silver. Converting those to grams is a modern calculation
 * and there are two in circulation, so both are carried here and the screen
 * names which it is using.
 */

export type NisabStandard = 'common' | 'classical';

/**
 * The two conversions of the same ruling, in grams.
 *
 * `common` takes the mithqāl at 4.25g and the dirham at 2.975g, which is the
 * figure most zakat bodies publish. `classical` is the older reckoning. They
 * differ by about 3%, which is small against the ten-fold gap between the gold
 * and silver thresholds — but it is not nothing, and picking one silently
 * would be picking one silently.
 */
export const NISAB_GRAMS: Record<NisabStandard, { gold: number; silver: number }> = {
  common: { gold: 85, silver: 595 },
  classical: { gold: 87.48, silver: 612.36 },
};

/** The share of qualifying wealth that is due. One fortieth — Abu Dawud 1572. */
export const ZAKAT_RATE = 0.025;

export type PricePerGram = { gold: number; silver: number };

/** When these prices were read, as the upstream reported it. */
export const PRICED_AT = "2026-08-29T02:00:20.69+00:00";

/** Who priced it. Shown to the reader, because a number owes its source. */
export const PRICE_SOURCE = "gold-api.com (spot)";

export const PRICES: Readonly<Record<string, PricePerGram>> = {
  "USD": {
    "gold": 143.28,
    "silver": 2.14
  },
  "GBP": {
    "gold": 105.72,
    "silver": 1.58
  },
  "EUR": {
    "gold": 123.41,
    "silver": 1.84
  },
  "CAD": {
    "gold": 198.98,
    "silver": 2.97
  },
  "AUD": {
    "gold": 199.81,
    "silver": 2.98
  },
  "PKR": {
    "gold": 39818.18,
    "silver": 594.21
  },
  "INR": {
    "gold": 13687.76,
    "silver": 204.26
  },
  "MYR": {
    "gold": 576.8,
    "silver": 8.61
  },
  "ZAR": {
    "gold": 2305.66,
    "silver": 34.41
  },
  "AED": {
    "gold": 526.18,
    "silver": 7.85
  }
};

export const CURRENCIES = Object.keys(PRICES);
