/**
 * Regenerates the clip list inside `docs/audio-recording-brief.md`.
 *
 * Run: `npm run audio:brief`   Check only: `npm run audio:brief -- --check`
 *
 * ## Why this exists
 *
 * The brief already said "Generated from `src/content/recitations.ts`" and
 * nothing generated it. That is the worst state a document can be in: it
 * claims to be derived, so nobody re-reads it against the source, and it
 * drifts silently. A reciter works from this file, so a drifted line here is
 * a session re-recorded.
 *
 * ## What it reads
 *
 * `docs/audio-manifest.csv`, not the content tree — the manifest is already
 * generated from `src/content/` and already guarded by
 * `npm run audio:manifest -- --check`. Deriving the brief from the manifest
 * makes one chain (content → manifest → brief) instead of two regexes over
 * the guides that can disagree with each other.
 *
 * ## What it does not touch
 *
 * Everything outside the two marked regions. The prose — what the recording
 * is for, the register, the format, the rights — is hand-written and worth
 * more than anything a script would put there. Generation is confined to the
 * count line and the clip list, so regenerating can never eat the writing.
 *
 * ## Scope: the clips a screen is waiting for
 *
 * Only recitations that are unrecorded AND used in a guide. The everyday
 * adhkar — sleeping, waking, leaving the house — are unrecorded too, but no
 * screen plays them, so commissioning them buys nothing until one does. The
 * manifest lists them; this brief deliberately does not.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const briefPath = join(root, 'docs/audio-recording-brief.md');
const manifestPath = join(root, 'docs/audio-manifest.csv');

/** Minimal RFC4180 reader — the sheet carries quoted commas in translations. */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let quoted = false;
  for (let i = 0; i < text.length; i += 1) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i += 1; }
      else if (c === '"') quoted = false;
      else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c !== '\r') field += c;
  }
  if (field || row.length) { row.push(field); rows.push(row); }
  const [header, ...body] = rows.filter((r) => r.some((v) => v !== ''));
  return body.map((r) => Object.fromEntries(header.map((h, i) => [h, r[i] ?? ''])));
}

const rows = parseCsv(readFileSync(manifestPath, 'utf8'));

/*
  "Used in" is the step title the manifest resolved. A clip with no step is one
  the app has no screen for yet, and it stays out — see the header.
*/
const clips = rows.filter(
  (r) => r.Status !== 'Ready' && r['Used in'] && r['Used in'] !== 'Not used in a guide',
);

if (clips.length === 0) {
  console.error('No unrecorded clips are wired to a step. Nothing to brief.');
  process.exit(1);
}

/*
  RTL is wrapped in a div rather than left bare: a reciter opens this in a
  browser or a Word preview, and unmarked Arabic beside Latin punctuation
  reorders the line. `##` sizes it — this is the text being read aloud, so it
  is the largest thing on the page.
*/
function block(r) {
  const name = r.Recitation + (r.Part && r.Part !== '—' ? ` — ${r.Part}` : '');
  return `#### \`${r.File}\`

<div dir="rtl" lang="ar">

## ${r.Arabic}

</div>

*${r.Transliteration}*

> ${r.Translation}

<sub>${name} · said at: ${r['Used in']}</sub>`;
}

const countRegion = `**${clips.length} clips.** Generated by \`npm run audio:brief\` from
\`docs/audio-manifest.csv\`; regenerate rather than editing by hand, so the text a
reciter reads is the text the app shows.`;

const clipsRegion = clips.map(block).join('\n\n');

function replaceRegion(text, name, body) {
  const open = `<!-- GENERATED:${name} -->`;
  const close = `<!-- /GENERATED:${name} -->`;
  const start = text.indexOf(open);
  const end = text.indexOf(close);
  if (start === -1 || end === -1) {
    console.error(`Marker ${open} … ${close} is missing from the brief. Not guessing where it went.`);
    process.exit(1);
  }
  return text.slice(0, start + open.length) + '\n' + body + '\n' + text.slice(end);
}

const current = readFileSync(briefPath, 'utf8');
let next = replaceRegion(current, 'COUNT', countRegion);
next = replaceRegion(next, 'CLIPS', clipsRegion);

if (process.argv.includes('--check')) {
  if (next !== current) {
    console.error('Recording brief is out of date. Run: npm run audio:brief');
    process.exit(1);
  }
  console.log(`Recording brief up to date — ${clips.length} clips.`);
} else {
  writeFileSync(briefPath, next);
  console.log(`Wrote ${clips.length} clips to docs/audio-recording-brief.md.`);
}
