/**
 * A dated snapshot of the gold and silver nisab.
 *
 * Run: `npm run zakat:nisab` (needs a network connection)
 * Writes `src/content/nisab.ts`.
 *
 * ## Why a snapshot and not a runtime call
 *
 * The price moves daily and the app must not. Every source in this project is
 * a build-time tool — if all of them vanished tomorrow the app would not
 * notice — and a zakat screen that needs a signal to show you a number is a
 * zakat screen that fails on a plane. So the figure ships in the bundle,
 * refreshes whenever an OTA ships, and the screen is honest about its own age
 * in between.
 *
 * ## Why ummahapi rather than the API the plan named
 *
 * `docs/build-order.md` Phase 12 specifies islamicapi and an API key that
 * "lives in your environment and never ships". ummahapi serves the same
 * numbers with **no key at all** — 5,000 requests per fifteen minutes, which
 * for a script that runs once a release is not a limit — so the whole key
 * problem disappears rather than being managed.
 *
 * ⚠️ `docs/expansion-plan.md` §1.3 REJECTS ummahapi, and that rejection stands
 * where it was made: its hadith API cites volume-and-page rather than hadith
 * numbers, so nothing can check it. That objection does not reach a spot
 * price. A gold price is not a narration, it is a number with a timestamp and
 * a named upstream, and it is checkable against any dealer.
 *
 * ## What is taken, and what is deliberately not
 *
 * Taken: the price per gram, and nothing else.
 *
 * NOT taken: `/api/zakat/calculate`, which returns a verdict computed on rules
 * this project cannot inspect. The arithmetic here is 2.5% and belongs in the
 * app where it can be read; the rules about what counts belong to a person.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * The currencies the snapshot carries.
 *
 * A short list rather than the hundred the API offers: every one is a separate
 * request and a line in the bundle, and a reader whose currency is missing is
 * told so plainly rather than shown a number in the wrong money.
 */
const CURRENCIES = ['USD', 'GBP', 'EUR', 'CAD', 'AUD', 'PKR', 'INR', 'MYR', 'ZAR', 'AED'];

const get = async (currency) => {
  const url = `https://ummahapi.com/api/zakat/prices?currency=${currency}`;
  const response = await fetch(url, { headers: { 'user-agent': 'new-muslim-guide/nisab' } });
  if (!response.ok) throw new Error(`${response.status} ${url}`);
  const body = await response.json();
  if (!body?.success || !body?.data) throw new Error(`${currency}: no data`);
  return body.data;
};

console.log('Nisab snapshot — gold and silver per gram, from ummahapi\n');

const prices = {};
let asOf;
let source;

for (const currency of CURRENCIES) {
  const data = await get(currency);

  if (!data.currency_supported) {
    throw new Error(`${currency}: the API says it does not support this currency`);
  }
  /*
    A fallback price is a stale or estimated one. Shipping it would put a
    number on a zakat screen that nobody can trace to a market, which is worse
    than the screen saying it does not know.
  */
  if (data.is_fallback) throw new Error(`${currency}: the API returned a fallback price`);

  for (const field of ['gold_price_per_gram', 'silver_price_per_gram']) {
    if (typeof data[field] !== 'number' || !(data[field] > 0)) {
      throw new Error(`${currency}: ${field} is not a positive number`);
    }
  }
  /* Gold is worth vastly more per gram than silver. If that ever inverts, the
     response is wrong and no zakat figure should be built on it. */
  if (data.gold_price_per_gram <= data.silver_price_per_gram) {
    throw new Error(`${currency}: gold is priced at or below silver — the response is wrong`);
  }

  prices[currency] = {
    gold: Number(data.gold_price_per_gram.toFixed(2)),
    silver: Number(data.silver_price_per_gram.toFixed(4)),
  };
  asOf ??= data.as_of;
  source ??= data.source;
  console.log(`  ${currency}  gold ${prices[currency].gold}  silver ${prices[currency].silver}`);
}

const file = `/**
 * What gold and silver cost, on the day this was last built.
 *
 * GENERATED by \`npm run zakat:nisab\`. Do not edit by hand.
 *
 * ⚠️ This is a SNAPSHOT and the screen must say so. The price moves daily and
 * this file does not; it refreshes when an OTA ships. A zakat figure presented
 * without its date is a figure somebody will act on months after it stopped
 * being true.
 *
 * The gram thresholds below are NOT from this API and not from any hadith. The
 * hadith give 20 dinars and 200 dirhams — Abu Dawud 1573, and Bukhari 1447 for
 * the five awāq of silver. Converting those to grams is a modern calculation
 * and there are two in circulation, so both are carried here and the screen
 * names which it is using.
 */

export type NisabStandard = 'common' | 'classical';

/**
 * The two conversions of the same ruling, in grams.
 *
 * \`common\` takes the mithqāl at 4.25g and the dirham at 2.975g, which is the
 * figure most zakat bodies publish. \`classical\` is the older reckoning. They
 * differ by about 3%, which is small against the ten-fold gap between the gold
 * and silver thresholds — but it is not nothing, and picking one silently
 * would be picking one silently.
 */
export const NISAB_GRAMS: Record<NisabStandard, { gold: number; silver: number }> = {
  common: { gold: 85, silver: 595 },
  classical: { gold: 87.48, silver: 612.36 },
};

/** The share of qualifying wealth that is due. One fortieth — Abu Dawud 1572. */
export const ZAKAT_RATE = 0.025;

export type PricePerGram = { gold: number; silver: number };

/** When these prices were read, as the upstream reported it. */
export const PRICED_AT = ${JSON.stringify(asOf)};

/** Who priced it. Shown to the reader, because a number owes its source. */
export const PRICE_SOURCE = ${JSON.stringify(source)};

export const PRICES: Readonly<Record<string, PricePerGram>> = ${JSON.stringify(prices, null, 2)};

export const CURRENCIES = Object.keys(PRICES);
`;

writeFileSync(join(root, 'src/content/nisab.ts'), file);
console.log(`\nPriced at ${asOf} — ${source}`);
console.log(`Wrote ${Object.keys(prices).length} currencies to src/content/nisab.ts`);
