/**
 * Generates `src/content/quran/juz30.ts` from the Quran Foundation API.
 *
 * Run: `node scripts/generate-juz30.mjs`  (needs a network connection)
 *
 * The content ships in the app, as everything in `src/content/` does — the
 * whole premise is that a dead signal changes nothing, so this runs when we
 * say so and writes a file, rather than the app fetching at runtime.
 *
 * ## Why generated rather than typed
 *
 * Five hundred and sixty-four ayahs is not something to transcribe. Every
 * character of Arabic in the output came over the wire from a published text
 * and none of it was written from memory, which is the only way this file
 * could exist at all given what CLAUDE.md says about Arabic.
 *
 * ## Which fields, and why these
 *
 * - `text_imlaei` — the simplified script, which is what the rest of the app
 *   already sets. The API also serves Uthmani; taking that would change the
 *   script style of the whole app through the back door.
 * - Translation 20, Saheeh International. Chosen for consistency: it is the
 *   same translation QuranEnc serves as `english_saheeh`, which is what
 *   `content:verify` already compares against.
 * - No transliteration. Settled deliberately — a Latin line under the ayah is
 *   read *instead of* the Arabic, and people end up memorising English letters
 *   and still cannot open a mushaf. The audio does that job better.
 *
 * ⚠️ LICENCE UNRESOLVED. Saheeh International is a copyrighted translation
 * distributed by these APIs without published reuse terms. The attribution is
 * recorded in the generated file, and this needs settling in the same
 * conversation as the IslamHouse one before the app ships publicly.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const FIRST = 78;
const LAST = 114;
const TRANSLATION = 20;

const get = async (url) => {
  const response = await fetch(url, { headers: { 'user-agent': 'new-muslim-guide/juz30' } });
  if (!response.ok) throw new Error(`${response.status} ${url}`);
  return response.json();
};

/**
 * The translation as prose.
 *
 * Footnote markers come through as `<sup foot_note=197829>1</sup>`, and
 * stripping tags alone leaves the digit welded to the word before it — "He is
 * Allāh, [who is] One,1". The whole element goes, contents included.
 *
 * The footnotes themselves are dropped rather than carried. They are long,
 * they are a different reading experience, and a memorisation screen is not
 * where somebody stops to read a paragraph about the meaning of ar-Rahmān.
 */
const strip = (html) =>
  html
    .replace(/<sup[^>]*>.*?<\/sup>/g, '')
    .replace(/<[^>]*>/g, '')
    .replace(/\s+/g, ' ')
    .trim();

console.log(`Fetching surahs ${FIRST}–${LAST}…`);

const { chapters } = await get('https://api.quran.com/api/v4/chapters?language=en');
const meta = new Map(chapters.map((c) => [c.id, c]));

const surahs = [];
for (let n = FIRST; n <= LAST; n += 1) {
  const info = meta.get(n);
  const data = await get(
    `https://api.quran.com/api/v4/verses/by_chapter/${n}` +
      `?fields=text_imlaei&translations=${TRANSLATION}&per_page=300`,
  );

  surahs.push({
    number: n,
    name: info.name_simple,
    // The name as it is actually written. A convert meets these on a mosque
    // wall and in a mushaf's contents long before they can read a whole ayah,
    // and recognising the shape of "الإخلاص" is the first Arabic reading most
    // people do without noticing they are doing it.
    nameArabic: info.name_arabic,
    meaning: info.translated_name.name,
    place: info.revelation_place,
    ayahs: data.verses.map((verse) => ({
      number: verse.verse_number,
      arabic: verse.text_imlaei,
      translation: strip(verse.translations?.[0]?.text ?? ''),
    })),
  });
  process.stdout.write(`  ${n} ${info.name_simple} — ${data.verses.length}\n`);
}

const total = surahs.reduce((n, s) => n + s.ayahs.length, 0);
if (total !== 564) throw new Error(`Expected 564 ayahs across Juz 30, got ${total}`);

const body = surahs
  .map(
    (s) => `  {
    number: ${s.number},
    name: ${JSON.stringify(s.name)},
    nameArabic: ${JSON.stringify(s.nameArabic)},
    meaning: ${JSON.stringify(s.meaning)},
    place: ${JSON.stringify(s.place)},
    ayahs: [
${s.ayahs
  .map(
    (a) =>
      `      { number: ${a.number}, arabic: ${JSON.stringify(a.arabic)}, translation: ${JSON.stringify(a.translation)} },`,
  )
  .join('\n')}
    ],
  },`,
  )
  .join('\n');

const file = `/**
 * Juz 30 — surahs 78 to 114, the short ones at the end of the mushaf.
 *
 * GENERATED by \`node scripts/generate-juz30.mjs\`. Do not edit by hand: a
 * correction made here is lost the next time it runs, and a correction that
 * needs making belongs upstream, where the text is published.
 *
 * ${surahs.length} surahs, ${total} ayahs. Every character of Arabic came over the wire from
 * api.quran.com rather than from memory, which is the only way a file this
 * size could exist under this project's rules about Arabic text.
 *
 * The Arabic is Imlaei — the simplified script the rest of the app already
 * sets. The API also serves Uthmani, and taking that would have changed the
 * script style of the whole app through the back door.
 *
 * There is no transliteration, deliberately. A Latin line under an ayah is
 * read *instead of* the Arabic, and someone who learns that way memorises
 * English letters and still cannot open a mushaf. Recitation does that job.
 *
 * ⚠️ LICENCE UNRESOLVED — see the attribution below. Neither the translation
 * nor the API publishes reuse terms, and this needs settling before the app
 * ships publicly.
 *
 * ⚠️ REVIEW REQUIRED — the text is published and unedited, and nobody
 * qualified has yet read this file back against a mushaf.
 */

/** Where the text and the translation came from. A licence obligation. */
export const JUZ30_SOURCE = {
  arabic: 'Imlaei text from api.quran.com (Quran Foundation)',
  translation: 'Saheeh International',
  fetched: ${JSON.stringify(new Date().toISOString().slice(0, 10))},
} as const;

export type Ayah = {
  number: number;
  arabic: string;
  translation: string;
};

export type Surah = {
  number: number;
  /** Transliterated name, as it is normally referred to — "An-Nas". */
  name: string;
  /** The name in Arabic — "الناس". */
  nameArabic: string;
  /** What the name means in English — "Mankind". */
  meaning: string;
  place: string;
  ayahs: readonly Ayah[];
};

export const JUZ_30: readonly Surah[] = [
${body}
];

/**
 * The order people actually learn them: backwards through the mushaf.
 *
 * Not shortest-first, which the data contradicts — 110 and 103 are shorter
 * than 114. Backwards is how it is taught, it is contiguous so there is never
 * a question about what comes next, and it front-loads the three *quls*, which
 * are the highest-utility surahs in the book: said in prayer, after prayer,
 * and for ruqyah.
 */
export const LEARNING_ORDER: readonly Surah[] = [...JUZ_30].reverse();

export function getSurah(number: number): Surah | undefined {
  return JUZ_30.find((surah) => surah.number === number);
}
`;

mkdirSync(join(root, 'src/content/quran'), { recursive: true });
writeFileSync(join(root, 'src/content/quran/juz30.ts'), file);
console.log(`\nWrote src/content/quran/juz30.ts — ${surahs.length} surahs, ${total} ayahs.`);
