/**
 * Al-Fatiha — the surah recited in every rak'ah of every prayer.
 *
 * GENERATED by `node scripts/generate-juz30.mjs`. Do not edit by hand.
 *
 * Seven ayahs, and the first is the basmala. That numbering is what the seven
 * bundled clips in `src/content/audio.ts` are cut to, and the generator
 * asserts it rather than trusting it — a text that numbered the basmala out of
 * the surah would leave every clip playing against the wrong line, silently.
 *
 * Same source, same script and same translation as `juz30.ts`, so the two
 * read as one book rather than as two imports.
 *
 * ⚠️ REVIEW REQUIRED, and the translation's terms — both exactly as recorded
 * in the header of `juz30.ts`.
 */

import type { Surah } from './juz30';

export const AL_FATIHA: Surah = {
    number: 1,
    name: "Al-Fatihah",
    nameArabic: "الفاتحة",
    meaning: "The Opener",
    place: "makkah",
    ayahs: [
      { number: 1, arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", translation: "In the name of Allah, the Gracious, the Merciful." },
      { number: 2, arabic: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", translation: "Praise be to Allah, Lord of the Worlds." },
      { number: 3, arabic: "الرَّحْمَٰنِ الرَّحِيمِ", translation: "The Most Gracious, the Most Merciful." },
      { number: 4, arabic: "مَالِكِ يَوْمِ الدِّينِ", translation: "Master of the Day of Judgment." },
      { number: 5, arabic: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ", translation: "It is You we worship, and upon You we call for help." },
      { number: 6, arabic: "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ", translation: "Guide us to the straight path." },
      { number: 7, arabic: "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ", translation: "The path of those You have blessed, not of those against whom there is anger, nor of those who are misguided." },
    ],
  };
