/**
 * What the app says about Hisn al-Muslim that the book does not say itself.
 *
 * ## Hand-written, and deliberately not generated
 *
 * `hisn.ts` is regenerated by `npm run hisn` and every character in it came
 * over the wire. This file is the opposite, and it is the same arrangement
 * `moments.ts` already uses for the same reason: a generator would overwrite
 * it. Adding an entry here is a decision, and nothing about it is derivable
 * from the book.
 *
 * ## What belongs here, and what does not
 *
 * The line between the two files is whether the book states it.
 *
 * The book states the repeat count — `(ثلاثَ مرَّاتٍ)` — so `repeat` is read
 * off the page by the generator, cross-checked against IslamHouse's English,
 * and lives in `hisn.ts`. Reading what is written is a transformation.
 *
 * The book does NOT state which of its 318 lines are words a person says.
 * That has to be decided, and the decisions are not close calls dressed up as
 * hard ones — line 1269155 of the after-prayer adhkār is the complete string
 * "After every prayer.", and the first line of the sleep adhkār is "One should
 * join his palms closely, blow breath in them, and recite in them:". Both are
 * instructions. The whole of "The Merit of Dhikr" — 16 lines — is narration
 * about the reward for remembrance and contains nothing to recite. `kind`
 * marks all of these `quoted` or `prose` on the strength of the book's
 * punctuation, which is not the same question.
 *
 * ## ⚠️ Empty, and that is the honest state
 *
 * Nothing is annotated yet. An absent entry means "no one has decided",
 * which is true, and a screen must treat it as such rather than defaulting to
 * `recited: true` — defaulting is how an unreviewed line ends up under a
 * counter telling somebody to say it three times.
 *
 * These are religious judgements and they need a qualified reviewer, not a
 * model and not a developer. `docs/scholarly-review.md` is where they get
 * cleared; `docs/hisn-dataset-plan.md` §5 is why it matters more here than
 * anywhere else in the app — these annotations are what the public dataset
 * would publish, and a wrong one propagates into every app that consumes it.
 *
 * `npm run hisn:check` fails if an entry points at a line id the book no
 * longer has, which is the drift this keying is exposed to.
 */

export type HisnAnnotation = {
  /**
   * Is this line words a person says?
   *
   * `false` for an instruction or a narration about the virtue of dhikr.
   * Absent means undecided, which is not the same as `false`.
   */
  recited?: boolean;
  /**
   * Which of the two sittings this line belongs to.
   *
   * Absent means BOTH, and that is the book's own position rather than a gap:
   * Hisn al-Muslim prints one list for the morning and the evening and marks
   * only the few that belong to one sitting. Twenty-three of the twenty-nine
   * carry no mark, so they are said at both, and the app claims nothing the
   * book does not.
   *
   * Set only where the book says so IN THE TEXT — `(مائةَ مرَّةٍ إذا أصبحَ)`,
   * `(ثلاثَ مرَّاتٍ إذا أمسى)`. That is transcription, not a ruling, which is
   * why these are filled in and the rest of the split is not a question.
   */
  time?: 'morning' | 'evening';
  /**
   * The evening opening for a line whose wording changes, verbatim from the
   * book's own footnote.
   *
   * Six lines in, `اللَّهُمَّ إِنِّي أَصْبَحْتُ` means "O Allah, I have reached the
   * morning" — said at sunset it is not a variant, it is wrong. The book knows
   * and gives the substitution in a footnote: `وإذا أمسى قال: اللَّهم إني أمسيت`.
   *
   * ⚠️ The footnote ends in an ellipsis: "and the rest as above". So the app
   * SHOWS the substitution beside the morning wording rather than splicing a
   * complete evening text — a spliced string would appear verbatim nowhere,
   * and assembling one is the one place invention could enter this file.
   */
  eveningOpening?: string;
  /**
   * This row is the tail of the one above it, split by the publisher's
   * pagination rather than because it is a separate thing to say.
   *
   * Two of the sleep adhkār are verse endings — Sūrat an-Nās finishes on its
   * own row, and al-Baqarah 286 sits under 285. Shown as separate cards they
   * read as two texts; a reader is being asked to say one.
   */
  continues?: boolean;
  /**
   * Why, in a few words, for the reviewer coming after.
   *
   * Every entry in this file carries one. An annotation without a stated
   * reason is indistinguishable from a guess, and the point of the file is
   * that a person can check each line against the book.
   */
  reason?: string;
  /** ISO date a qualified reviewer cleared this entry. */
  reviewed?: string;
};

/**
 * Keyed by IslamHouse's line id — the same key `moments.ts` uses.
 *
 * ⚠️ These eight were read one at a time and are NOT reviewed: `reviewed` is
 * absent on every one, and a reviewer should still see them. They are here
 * because each is a question of what the sentence IS, not of what the ruling
 * is — "one should join his palms and blow into them" is an instruction in any
 * reading of the Arabic, and "(ثلاث مرات)" is a count for the lines above it.
 * Nothing here decides a wording, a grading, or which sitting a line belongs
 * to; those stay untouched.
 *
 * The rest of the four sittings — 54 of 59 lines — needed no entry. An earlier
 * estimate of "59 judgements" treated the whole pile as one problem and was
 * wrong by an order of magnitude.
 */
export const HISN_ANNOTATIONS: Readonly<Record<number, HisnAnnotation>> = {
  // Morning and evening adhkār
  1269191: {
    recited: false,
    reason: "the compiler's own opening praise, before the adhkār begin",
  },
  1269211: { recited: false, reason: 'a count for the three sūrahs above, not a text' },

  // …and the six the book marks for one sitting or the other. Transcribed
  // from the parenthesis printed in the line, or from its own footnote.
  1269255: { time: 'morning', reason: 'the line says (مائةَ مرَّةٍ إذا أصبحَ)' },
  1269257: { time: 'morning', reason: 'the line says (ثلاثَ مرَّاتٍ إذا أصبحَ)' },
  1269259: { time: 'morning', reason: 'the line says (إذا أصبحَ)' },
  1269263: { time: 'evening', reason: 'the line says (ثلاثَ مرَّاتٍ إذا أمسى)' },
  1269223: {
    eveningOpening: 'اللَّهم إني أمسيت',
    reason: "the book's footnote: وإذا أمسى قال: اللَّهم إني أمسيت",
  },
  1269226: {
    eveningOpening: 'اللَّهم ما أمسى بي',
    reason: "the book's footnote: وإذا أمسى قال: اللَّهم ما أمسى بي...",
  },

  // Adhkār of sleep
  1269268: { recited: false, reason: 'an instruction: join the palms and blow into them' },
  1269283: { recited: true, continues: true, reason: 'the last words of Sūrat an-Nās' },
  1269284: { recited: false, reason: 'an instruction: wipe over the body afterwards' },
  1269289: { recited: true, continues: true, reason: 'al-Baqarah 286, under 285 above it' },
  1269309: {
    recited: false,
    reason: 'an instruction to recite as-Sajdah and al-Mulk, not their text',
  },

  // Adhkār after the prayer
  1269173: { recited: false, reason: 'a label on the lines above: after every prayer' },
};

/**
 * What the app knows about a line, which today is nothing for every line.
 *
 * Returns `undefined` rather than a default so a caller has to handle "not
 * decided" explicitly.
 */
export function annotationFor(lineId: number): HisnAnnotation | undefined {
  return HISN_ANNOTATIONS[lineId];
}
