/**
 * What the app says about Hisn al-Muslim that the book does not say itself.
 *
 * ## Hand-written, and deliberately not generated
 *
 * `hisn.ts` is regenerated by `npm run hisn` and every character in it came
 * over the wire. This file is the opposite, and it is the same arrangement
 * `moments.ts` already uses for the same reason: a generator would overwrite
 * it. Adding an entry here is a decision, and nothing about it is derivable
 * from the book.
 *
 * ## What belongs here, and what does not
 *
 * The line between the two files is whether the book states it.
 *
 * The book states the repeat count — `(ثلاثَ مرَّاتٍ)` — so `repeat` is read
 * off the page by the generator, cross-checked against IslamHouse's English,
 * and lives in `hisn.ts`. Reading what is written is a transformation.
 *
 * The book does NOT state which of its 318 lines are words a person says.
 * That has to be decided, and the decisions are not close calls dressed up as
 * hard ones — line 1269155 of the after-prayer adhkār is the complete string
 * "After every prayer.", and the first line of the sleep adhkār is "One should
 * join his palms closely, blow breath in them, and recite in them:". Both are
 * instructions. The whole of "The Merit of Dhikr" — 16 lines — is narration
 * about the reward for remembrance and contains nothing to recite. `kind`
 * marks all of these `quoted` or `prose` on the strength of the book's
 * punctuation, which is not the same question.
 *
 * ## ⚠️ Empty, and that is the honest state
 *
 * Nothing is annotated yet. An absent entry means "no one has decided",
 * which is true, and a screen must treat it as such rather than defaulting to
 * `recited: true` — defaulting is how an unreviewed line ends up under a
 * counter telling somebody to say it three times.
 *
 * These are religious judgements and they need a qualified reviewer, not a
 * model and not a developer. `docs/scholarly-review.md` is where they get
 * cleared; `docs/hisn-dataset-plan.md` §5 is why it matters more here than
 * anywhere else in the app — these annotations are what the public dataset
 * would publish, and a wrong one propagates into every app that consumes it.
 *
 * `npm run hisn:check` fails if an entry points at a line id the book no
 * longer has, which is the drift this keying is exposed to.
 */

export type HisnAnnotation = {
  /**
   * Is this line words a person says?
   *
   * `false` for an instruction or a narration about the virtue of dhikr.
   * Absent means undecided, which is not the same as `false`.
   */
  recited?: boolean;
  /**
   * Which of the two sittings this line belongs to.
   *
   * The book prints one combined morning-and-evening list and marks only a
   * handful of lines `إذا أصبحَ` or `إذا أمسى`. For the rest it is a judgement,
   * and for a few the WORDING changes between the two — footnote 112 says the
   * evening form of `اللَّهُمَّ مَا أَصْبَحَ بِي` is `اللَّهُمَّ مَا أَمْسَى بِي`.
   * A variant wording is a religious text and must be recorded verbatim from
   * the book's own footnote, never conjugated by hand.
   */
  time?: 'morning' | 'evening' | 'both';
  /** Why, in a few words, for the reviewer coming after. */
  reason?: string;
  /** ISO date a qualified reviewer cleared this entry. */
  reviewed?: string;
};

/** Keyed by IslamHouse's line id — the same key `moments.ts` uses. */
export const HISN_ANNOTATIONS: Readonly<Record<number, HisnAnnotation>> = {};

/**
 * What the app knows about a line, which today is nothing for every line.
 *
 * Returns `undefined` rather than a default so a caller has to handle "not
 * decided" explicitly.
 */
export function annotationFor(lineId: number): HisnAnnotation | undefined {
  return HISN_ANNOTATIONS[lineId];
}
