/**
 * What the app says about Hisn al-Muslim that the book does not say itself.
 *
 * ## Hand-written, and deliberately not generated
 *
 * `hisn.ts` is regenerated by `npm run hisn` and every character in it came
 * over the wire. This file is the opposite, and it is the same arrangement
 * `moments.ts` already uses for the same reason: a generator would overwrite
 * it. Adding an entry here is a decision, and nothing about it is derivable
 * from the book.
 *
 * ## What belongs here, and what does not
 *
 * The line between the two files is whether the book states it.
 *
 * The book states the repeat count — `(ثلاثَ مرَّاتٍ)` — so `repeat` is read
 * off the page by the generator, cross-checked against IslamHouse's English,
 * and lives in `hisn.ts`. Reading what is written is a transformation.
 *
 * The book does NOT state which of its 318 lines are words a person says.
 * That has to be decided, and the decisions are not close calls dressed up as
 * hard ones — line 1269155 of the after-prayer adhkār is the complete string
 * "After every prayer.", and the first line of the sleep adhkār is "One should
 * join his palms closely, blow breath in them, and recite in them:". Both are
 * instructions. The whole of "The Merit of Dhikr" — 16 lines — is narration
 * about the reward for remembrance and contains nothing to recite. `kind`
 * marks all of these `quoted` or `prose` on the strength of the book's
 * punctuation, which is not the same question.
 *
 * ## ⚠️ Empty, and that is the honest state
 *
 * Nothing is annotated yet. An absent entry means "no one has decided",
 * which is true, and a screen must treat it as such rather than defaulting to
 * `recited: true` — defaulting is how an unreviewed line ends up under a
 * counter telling somebody to say it three times.
 *
 * These are religious judgements and they need a qualified reviewer, not a
 * model and not a developer. `docs/scholarly-review.md` is where they get
 * cleared; `docs/hisn-dataset-plan.md` §5 is why it matters more here than
 * anywhere else in the app — these annotations are what the public dataset
 * would publish, and a wrong one propagates into every app that consumes it.
 *
 * `npm run hisn:check` fails if an entry points at a line id the book no
 * longer has, which is the drift this keying is exposed to.
 */

export type HisnAnnotation = {
  /**
   * Is this line words a person says?
   *
   * `false` for an instruction or a narration about the virtue of dhikr.
   * Absent means undecided, which is not the same as `false`.
   */
  recited?: boolean;
  /**
   * Which of the two sittings this line belongs to.
   *
   * Absent means BOTH, and that is the book's own position rather than a gap:
   * Hisn al-Muslim prints one list for the morning and the evening and marks
   * only the few that belong to one sitting. Twenty-three of the twenty-nine
   * carry no mark, so they are said at both, and the app claims nothing the
   * book does not.
   *
   * Set only where the book says so IN THE TEXT — `(مائةَ مرَّةٍ إذا أصبحَ)`,
   * `(ثلاثَ مرَّاتٍ إذا أمسى)`. That is transcription, not a ruling, which is
   * why these are filled in and the rest of the split is not a question.
   */
  time?: 'morning' | 'evening';
  /**
   * This row is the tail of the one above it, split by the publisher's
   * pagination rather than because it is a separate thing to say.
   *
   * Two of the sleep adhkār are verse endings — Sūrat an-Nās finishes on its
   * own row, and al-Baqarah 286 sits under 285. Shown as separate cards they
   * read as two texts; a reader is being asked to say one.
   */
  continues?: boolean;
  /**
   * How many times, where the book states the count on a DIFFERENT row.
   *
   * Hisn al-Muslim prints the three Quls and then a bare row reading
   * `(ثلاثَ مرَّاتٍ)`, which is the count for the three above it rather than a
   * text of its own. The generator refuses to guess that — it reads a count
   * only where it sits beside the words — so the association is made here,
   * where a person can see which rows it was attached to.
   */
  repeat?: number;
  /**
   * Cut this row into the separate things it actually asks for.
   *
   * The book sometimes prints several dhikr in one row with the counts between
   * them — `سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَاللَّهُ أَكْبَرُ (ثلاثاً وثلاثين) …`.
   * Left whole it asks a reader to say all of it thirty-three times and shows
   * "(thirty-three times)" inside the duʿa as though it were part of the words.
   *
   * Each part names its own text rather than a marker to cut at, because the
   * English cannot be cut at the same points: IslamHouse prints a
   * transliteration first and the translation as one trailing parenthetical,
   * so the meaning of the first dhikr sits nowhere near it.
   *
   * ⚠️ Every string here is a VERBATIM substring of the row, sliced out of
   * `hisn.ts` by a script rather than typed, and `npm run narration:check`
   * fails if one stops matching. That is what stops this becoming the place
   * where Arabic quietly gets rewritten.
   */
  parts?: readonly { arabic: string; english: string; repeat?: number }[];
  /**
   * ⚠️ WORDS CHANGED FROM THE BOOK'S OWN TEXT. The only field here that does.
   *
   * Everything else in this file describes the book. This edits it, so it is
   * deliberately awkward: each replacement names the exact string it replaces,
   * `npm run narration:check` fails if that string is not in the row, and the
   * check prints the total so a rewrite can never be silent.
   *
   * Both halves are lifted from the corpus, never typed. For the one entry
   * that uses this — `الصُّبْحِ` → `الفَجْرِ`, on Iyad's instruction — the
   * replacement appears vowelled elsewhere in the book, and the wāw before it
   * is left untouched so no string is assembled by hand. IslamHouse's own
   * English already renders that word "Fajr".
   */
  rewrite?: readonly { from: string; to: string }[];
  /**
   * Extra spans to pick out in the accent colour, beyond the ones the book
   * bracketed.
   *
   * For text that is instruction rather than duʿa — "ten times after the
   * Maghrib and Fajr prayers" trails the end of a line and reads as part of
   * the words until it is marked.
   */
  emphasis?: readonly string[];
  /**
   * Do not show this row at all: what it says is carried somewhere else.
   *
   * Different from `recited: false`, which shows the row as an instruction
   * because it tells the reader to do something. A row like `(ثلاثَ مرَّاتٍ)`
   * tells them nothing once its count sits on the three sūrahs it belonged to
   * — as its own card it read as a duʿa whose entire text was "Three times."
   */
  omit?: boolean;
  /**
   * Why, in a few words, for the reviewer coming after.
   *
   * Every entry in this file carries one. An annotation without a stated
   * reason is indistinguishable from a guess, and the point of the file is
   * that a person can check each line against the book.
   */
  reason?: string;
  /** ISO date a qualified reviewer cleared this entry. */
  reviewed?: string;
};

/**
 * Keyed by IslamHouse's line id — the same key `moments.ts` uses.
 *
 * ⚠️ These eight were read one at a time and are NOT reviewed: `reviewed` is
 * absent on every one, and a reviewer should still see them. They are here
 * because each is a question of what the sentence IS, not of what the ruling
 * is — "one should join his palms and blow into them" is an instruction in any
 * reading of the Arabic, and "(ثلاث مرات)" is a count for the lines above it.
 * Nothing here decides a wording, a grading, or which sitting a line belongs
 * to; those stay untouched.
 *
 * The rest of the four sittings — 54 of 59 lines — needed no entry. An earlier
 * estimate of "59 judgements" treated the whole pile as one problem and was
 * wrong by an order of magnitude.
 */
export const HISN_ANNOTATIONS: Readonly<Record<number, HisnAnnotation>> = {
  // Morning and evening adhkār
  1269191: {
    recited: false,
    reason: "the compiler's own opening praise, before the adhkār begin",
  },
  // The book prints the three Quls, then a row saying (ثلاثَ مرَّاتٍ). The count
  // belongs to them; the row belongs nowhere once it has been moved.
  1269196: { repeat: 3, reason: 'the (ثلاثَ مرَّاتٍ) row below the three Quls' },
  1269200: { repeat: 3, reason: 'the (ثلاثَ مرَّاتٍ) row below the three Quls' },
  1269205: { repeat: 3, reason: 'the (ثلاثَ مرَّاتٍ) row below the three Quls' },
  1269211: { omit: true, reason: 'the count above; carried onto the three Quls' },

  // …and the six the book marks for one sitting or the other. Transcribed
  // from the parenthesis printed in the line, or from its own footnote.
  1269255: { time: 'morning', reason: 'the line says (مائةَ مرَّةٍ إذا أصبحَ)' },
  1269257: { time: 'morning', reason: 'the line says (ثلاثَ مرَّاتٍ إذا أصبحَ)' },
  1269259: { time: 'morning', reason: 'the line says (إذا أصبحَ)' },
  1269263: { time: 'evening', reason: 'the line says (ثلاثَ مرَّاتٍ إذا أمسى)' },

  /*
    ⚠️ EDITORIAL, not transcribed — the only entry in this file that is not
    read off the page, and Iyad's call.

    The book prints the same dhikr twice: once at ten times (or once when
    tired), and once at a hundred times in the morning. In the morning both
    appeared and read as a duplicate. The hundred-times line is marked
    `إذا أصبحَ` and so is morning-only, so deleting the ten-times line outright
    would have left the EVENING sitting with neither. Confining it to the
    evening removes the duplicate without losing the dhikr.
  */
  1269252: {
    time: 'evening',
    reason: 'duplicate of the ×100 line in the morning, which is morning-only',
  },

  // Adhkār of sleep
  1269268: { recited: false, reason: 'an instruction: join the palms and blow into them' },
  1269283: { recited: true, continues: true, reason: 'the last words of Sūrat an-Nās' },
  1269284: { recited: false, reason: 'an instruction: wipe over the body afterwards' },
  1269289: { recited: true, continues: true, reason: 'al-Baqarah 286, under 285 above it' },
  1269309: {
    recited: false,
    reason: 'an instruction to recite as-Sajdah and al-Mulk, not their text',
  },

  // Adhkār after the prayer
  1269178: {
    reason:
      'ten times after Maghrib and Fajr; the count and the occasion are prose at the end of the row',
    repeat: 10,
    rewrite: [{ from: "الصُّبْحِ", to: "الفَجْرِ" }],
    emphasis: ["عَشْرَ مَرّاتٍ بَعْدَ صَلاةِ الْمَغْرِبِ وَالفَجْرِ"],
  },
  1269173: { omit: true, reason: 'a label on the rows above, not a step of its own' },
  /*
    Two rows where the book puts several dhikr in one, with the count printed
    between them. Each part below is a VERBATIM substring of the row — cut out
    of the data by a script rather than typed, and checked by
    `npm run narration:check` on every run.
  */
  1269156: {
    reason: 'four dhikr in one row: the tasbīh, tahmīd and takbīr are ×33 each',
    parts: [
      {
        arabic: "سُبْحَانَ اللَّهِ",
        english: "Glory be to Allah",
        repeat: 33,
      },
      {
        arabic: "وَالْحَمْدُ لِلَّهِ",
        english: "and all praise is due to Allah",
        repeat: 33,
      },
      {
        arabic: "وَاللَّهُ أَكْبَرُ",
        english: "and Allah is the Greatest",
        repeat: 33,
      },
      {
        arabic: "لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
        english: "There is no god but Allah, alone with no partner. To Him belongs the sovereignty, and all praise is due to Him, and He is Competent over all things",
        repeat: 1,
      },
    ],
  },
  1269152: {
    reason: 'two dhikr in one row, with the count for the first printed between them',
    parts: [
      {
        arabic: "لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
        english: "There is no god but Allah, alone, with no partners. To Him belongs the sovereignty and all praise is due to Him, and He is Competent over all things",
        repeat: 3,
      },
      {
        arabic: "اللَّهُمَّ لاَ مَانِعَ لِمَا أَعْطَيْتَ، وَلاَ مُعْطِيَ لِمَا مَنَعْتَ، وَلاَ يَنْفَعُ ذَا الْجَدِّ مِنْكَ الجَدُّ",
        english: "O Allah, none can withhold what You have given, and none can give what You have withheld, and the greatness of the great will be of no avail to him against You",
      },
    ],
  },
};

/**
 * What the app knows about a line, which today is nothing for every line.
 *
 * Returns `undefined` rather than a default so a caller has to handle "not
 * decided" explicitly.
 */
export function annotationFor(lineId: number): HisnAnnotation | undefined {
  return HISN_ANNOTATIONS[lineId];
}
