/**
 * Where the book's occasions sit in an ordinary day.
 *
 * ## Hand-written, and deliberately not generated
 *
 * `hisn.ts` is regenerated by `npm run hisn` and every character in it came
 * over the wire. This file is the opposite: it is a set of editorial
 * judgements about placement, and a generator would overwrite them. Adding an
 * occasion here is a decision; nothing about it is derivable from the book.
 *
 * ## What is NOT claimed
 *
 * Only that an occasion belongs to a part of the day. Nothing here says a line
 * is a duʿa to recite, nothing promotes the book's text onto a teaching
 * surface, and the day screen still teaches only the nine supplications the
 * app owns and has had checked. This map is navigation.
 *
 * ## Why most of the book is absent
 *
 * 132 occasions, and roughly forty fit a day. The rest are the prayer's own
 * words, hajj, illness, death, weather, and the things people say to each
 * other — none of which has an hour. `DayMoment` is optional on a duʿa for the
 * same reason: a thing that does not belong to a moment should not be forced
 * into one, because a duʿa filed under the wrong moment is worse than one
 * filed nowhere. It is unfindable AND wrong.
 *
 * ⚠️ REVIEW REQUIRED — placement, not doctrine, but still a judgement. Whether
 * "supplication when the mount trips" belongs under travel is obvious; whether
 * the morning and evening adhkār belong under waking is less so, since half of
 * them are for the evening.
 */

import type { DayMoment } from '../duas';
import { HISN, type HisnOccasion } from './hisn';

/** IslamHouse row ids, grouped by the part of the day they belong to. */
export const OCCASIONS_BY_MOMENT: Readonly<Record<DayMoment, readonly number[]>> = {
  waking: [
    1268971, // waking from sleep
    1268990, // wearing a garment
    1268993, // wearing a new garment
    1269001, // taking off a garment
    1269190, // morning and evening adhkār
  ],
  washing: [
    1269004, // entering the bathroom
    1269007, // leaving the bathroom
    1269010, // before wudu
    1269013, // after wudu
  ],
  leaving: [
    1269020, // leaving the house
    1269025, // entering the house
    1269028, // going to the mosque
    1269035, // entering the mosque
    1269043, // leaving the mosque
    1269600, // entering a town
    1269603, // entering the market
  ],
  eating: [
    1269502, // before eating
    1269507, // finishing a meal
    1269512, // a guest for the host
    1269497, // breaking the fast
    1269518, // breaking the fast at someone's house
    1269521, // fasting while food is served
    1269528, // the first fruit of the season
  ],
  travel: [
    1269586, // riding
    1269592, // setting off
    1269606, // when the mount stumbles
    1269609, // the traveller, for those staying
    1269612, // those staying, for the traveller
    1269617, // takbir and tasbih on the road
    1269620, // at dawn on a journey
    1269623, // stopping somewhere
    1269626, // coming home
  ],
  night: [
    1269267, // going to sleep
    1269314, // turning over in the night
    1269317, // waking frightened
    1269320, // after a dream
    1269665, // hearing dogs at night
  ],
};

const BY_ID = new Map(HISN.map((occasion) => [occasion.id, occasion]));

/** The book's occasions for one part of the day, in the book's own order. */
export function hisnAt(moment: DayMoment): readonly HisnOccasion[] {
  return (OCCASIONS_BY_MOMENT[moment] ?? [])
    .map((id) => BY_ID.get(id))
    .filter((occasion): occasion is HisnOccasion => occasion !== undefined);
}

